export const DataBase={
  Clientes:[
    {
      id:0,
      nombre:'Martin',
      apellido:'Fernandez',
      dominio:'ABC123'
    },
    {
      id:1,
      nombre:'Alejandro',
      apellido:'Fernandez',
      dominio:'AC239OM'
    },
    {
      id:2,
      nombre:'Emilia',
      apellido:'Salomon',
      dominio:'SGS001'
    },
    {
      id:3,
      nombre:'Emilia',
      apellido:'Salomon',
      dominio:'SGS001'
    },
    {
      id:4,
      nombre:'Emilia',
      apellido:'Salomon',
      dominio:'SGS001'
    },
    {
      id:5,
      nombre:'Emilia',
      apellido:'Salomon',
      dominio:'SGS001'
    },
    {
      id:6,
      nombre:'Emilia',
      apellido:'Salomon',
      dominio:'SGS001'
    }
  ],
  Pagos:[
    {
      id:0,
      idCliente:0,
      idPoliza:0,
      fecha:'',
      monto:'',
      cupon:''
    },
    {
      id:1,
      idCliente:0,
      idPoliza:0,
      fecha:'',
      monto:'',
      cupon:''
    },
    {
      id:2,
      idCliente:0,
      idPoliza:0,
      fecha:'',
      monto:'',
      cupon:''
    }
  ],

  Polizas:[
    {
      id:0,
      empresa:'Allianz',
      tipo:'3ro Obligatorio',
      FechaInicio:'2018-01-25',
      FechaFin:'2019-01-25'
    },
    {
      id:1,
      empresa:'La Caja',
      tipo:'3ro Obligatorio',
      FechaInicio:'2017-11-21',
      FechaFin:'2018-11-21'
    }
  ],
  Usuarios:[
    {
      id:0,
      user:'admin',
      pass:'qweasd'
    }
  ],
}




