export const ClientsData = [
  {
    name:'Martin Alejandro',
    lastName:'Fernandez',
    nClient:1,
    domain:'AA123BB',
    payments:[
      {
        n:'',
        date:'',
        amount:'',
        coupon:''
      },
      {
        n:'',
        date:'',
        amount:'',
        coupon:''
      },
      {
        n:'',
        date:'',
        amount:'',
        coupon:''
      }
    ]
  },
  {
    name:'Alejandro',
    lastName:'Fernandez',
    nClient:2,
    domain:'AC239OM',
    payments:[
      {
        n:'',
        date:'',
        amount:'',
        coupon:''
      },
      {
        n:'',
        date:'',
        amount:'',
        coupon:''
      },
      {
        n:'',
        date:'',
        amount:'',
        coupon:''
      }
    ]
  },
];
